language: R
cache: packages
sudo: true
dist: trusty
warnings_are_errors: false
r:
  - devel
  - oldrel
  - release
    
env:
  global:
    # don't treat missing suggested packages as error
    - _R_CHECK_FORCE_SUGGESTS_=false
    # plotly_api_key (for posting to plot.ly)
    - secure: "WsvmMHN4YVhnk0bLRE04APcLbs5s4vWKSHjEdU0bPXd0xdMTzZeP5D7pxyF1983C+P5LpSnGHv4dgwLMBkNzxJwBR7/Ta7lfO1akYILWwxib+1DVbCqUH5Z4Ba1FSCQptIrLNGR3P7+0Lem4hEhqKdPKltFnxhnXO0Y+MeG71IQ="
    # MAPBOX_TOKEN (for testing `plot_mapbox()`)
    - secure: "QPBEqtLRdwb4ablJORzD0JdCT9ESe3nNdIehM1oxfcNKfpSdf2OFxH3TkeYY1nMpv0mLxiMNTy6xcj9Yk5MaaBCIA0P7q6OdZv9ruzQD1j3g84gP45KwBilbPGjb+/EvOS0fM25vR/pAmA8IyoUfPC2J8HwiNnW8DYdt/hJOJ9A="

before_install:
  - echo "Sys.setenv('plotly_username' = 'cpsievert')" > ~/.Rprofile
  # sf system dependencies
  - sudo add-apt-repository ppa:ubuntugis/ubuntugis-unstable --yes
  - sudo apt-get --yes --force-yes update -qq
  - sudo apt-get install --yes libudunits2-dev libproj-dev libgeos-dev libgdal-dev
  # make sure R pkgs are upt-to-date
  - Rscript -e 'update.packages(ask = FALSE)'

before_script:
  - if [[ "$TRAVIS_R_VERSION_STRING" == "release" ]]; then docker run -e MAPBOX_TOKEN=$MAPBOX_TOKEN -v $(pwd):/home/plotly --privileged cpsievert/plotly-orca R -e "devtools::install_deps('/home/plotly', dep = T); res <- devtools::test('/home/plotly', reporter='summary'); df <- as.data.frame(res); if (sum(df\$failed) > 0 || any(df\$error)) q(status=1)"; fi

# work around temporary travis + R 3.5 bug
r_packages: devtools  
